language: fsharp
sudo: required
dist: xenial
dotnet: 3.0

env:
  - solution: Sem4/Hw2/Task2_4/Task2_4.sln

before_build:
  - nuget restore $solution

build:
  - dotnet build $solution

script:
  - dotnet test $solution