  
language: fsharp
sudo: required
dist: xenial
dotnet: 3.0

env:
  - solution: Sem4/Hw4/Task4_2/Task4_2.sln

before_build:
  - nuget restore $solution

build:
  - dotnet build $solution

script:
  - dotnet test $solution