image: Visual Studio 2019

init:
  - git config --global core.autocrlf true

environment:
  matrix:
  - solution: Sem4/test1/Test1Task3/Test1Task3.sln

before_build:
  - nuget restore %solution%

build:
  project: $(solution)

test_script:
  - dotnet test %solution%