image: Visual Studio 2019

init:
  - git config --global core.autocrlf true

environment:
  matrix:
  - solution: sem4/hw2/Task2_4/Task2_4.sln

before_build:
  - nuget restore %solution%

build:
  project: $(solution)

test_script:
  - dotnet test %solution%
