// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Chat.proto

package com.example.grps;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.grpc.HelloRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
